spring:
  application:
    name: PayMyBuddy
  datasource:
    url: jdbc:mysql://localhost:3306/paymybuddy?serverTimezone=UTC
    username: root
    password:
springdoc:
  packages-to-scan: com.paymybuddy.webapp.resource
  show-actuator: true
  enable-spring-security: false
  swagger-ui:
    try-it-out-enabled: true
